name: Ruff and Mypy checks

on: push

jobs:
  pytest:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        run: make test
        env:
          TZ: "UTC"

  mypy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Run mypy
        run: make analyze

  linter:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Run ruff linter
        run: make format-check